// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cmo, use-js-string=true, version=5.9.1

//# unitInfo: Provides: H42n42
//# unitInfo: Requires: Eliom_client, Eliom_client_core, Eliom_content, Eliom_registration, Eliom_service, Js_of_ocaml__Dom, Js_of_ocaml__Dom_html, Js_of_ocaml__Firebug, Js_of_ocaml__Js, Js_of_ocaml_lwt__Lwt_js, Js_of_ocaml_lwt__Lwt_js_events, Lwt, Stdlib, Stdlib__Float, Stdlib__Hashtbl, Stdlib__List, Stdlib__Printf, Stdlib__Random
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    cst_0fpx_Press_Start_2P = "%.0fpx 'Press Start 2P'",
    cst_draw_zone$1 = "draw-zone",
    cst_h42n42_eliom = "h42n42.eliom",
    cst_px$1 = "px",
    cst_px_Press_Start_2P = "px 'Press Start 2P'",
    cst_white = "white",
    caml_jsstring_of_string = runtime.caml_jsstring_of_string,
    caml_maybe_attach_backtrace = runtime.caml_maybe_attach_backtrace,
    caml_wrap_exception = runtime.caml_wrap_exception;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) === 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) === 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   function caml_call3(f, a0, a1, a2){
    return (f.l >= 0 ? f.l : f.l = f.length) === 3
            ? f(a0, a1, a2)
            : runtime.caml_call_gen(f, [a0, a1, a2]);
   }
   function caml_call5(f, a0, a1, a2, a3, a4){
    return (f.l >= 0 ? f.l : f.l = f.length) === 5
            ? f(a0, a1, a2, a3, a4)
            : runtime.caml_call_gen(f, [a0, a1, a2, a3, a4]);
   }
   function caml_call10(f, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9){
    return (f.l >= 0 ? f.l : f.l = f.length) === 10
            ? f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9)
            : runtime.caml_call_gen
              (f, [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9]);
   }
   function caml_call11(f, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10){
    return (f.l >= 0 ? f.l : f.l = f.length) === 11
            ? f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10)
            : runtime.caml_call_gen
              (f, [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10]);
   }
   var
    dummy = 0,
    global_data = runtime.caml_get_global_data(),
    cst = "",
    eliom_compilation_unit_id_eZ0b = "eZ0bjX",
    global_data_path = [0, [0, "__global_data__", 0]],
    Lwt = global_data.Lwt,
    Js_of_ocaml_lwt_Lwt_js = global_data.Js_of_ocaml_lwt__Lwt_js,
    Stdlib_List = global_data.Stdlib__List,
    Stdlib = global_data.Stdlib,
    Js_of_ocaml_Firebug = global_data.Js_of_ocaml__Firebug,
    Stdlib_Random = global_data.Stdlib__Random,
    Js_of_ocaml_lwt_Lwt_js_events = global_data.Js_of_ocaml_lwt__Lwt_js_events,
    Js_of_ocaml_Js = global_data.Js_of_ocaml__Js,
    Js_of_ocaml_Dom_html = global_data.Js_of_ocaml__Dom_html,
    Js_of_ocaml_Dom = global_data.Js_of_ocaml__Dom,
    Stdlib_Float = global_data.Stdlib__Float,
    Stdlib_Printf = global_data.Stdlib__Printf,
    Eliom_content = global_data.Eliom_content,
    Eliom_service = global_data.Eliom_service,
    Eliom_client = global_data.Eliom_client,
    Eliom_registration = global_data.Eliom_registration,
    Eliom_client_core = global_data.Eliom_client_core,
    Stdlib_Hashtbl = global_data.Stdlib__Hashtbl,
    application_name = caml_call1(Eliom_client[18], 0),
    App =
      caml_call1
       (Eliom_registration[4], [0, application_name, global_data_path]);
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   caml_call1(Eliom_client[19], 0);
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   caml_call1(Eliom_client_core[56][2], eliom_compilation_unit_id_eZ0b);
   var
    main_service =
      caml_call3
       (Eliom_client_core[56][5],
        [0, "main_service"],
        [0,
         [0,
          [0, cst_h42n42_eliom, 24, 889, 917],
          [0, cst_h42n42_eliom, 24, 889, 917]]],
        "eZ0bjX1"),
    cst_draw_zone = cst_draw_zone$1,
    _a_ = [0, "css", [0, "h42n42.css", 0]],
    cst_h42n42 = "h42n42";
   caml_call11
    (App[2],
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     main_service,
     0,
     function(_at_, param){
      var
       _au_ = [0, [0, caml_call1(Eliom_content[3][1][8], cst_draw_zone), 0]],
       _av_ = [0, caml_call2(Eliom_content[3][1][248], _au_, 0), 0],
       _aw_ = caml_call2(Eliom_content[3][1][227], 0, _av_),
       _ax_ = caml_call1(Eliom_service[5], 0),
       _ay_ =
         caml_call10
          (Eliom_content[3][1][349], 0, 0, 0, _ax_, 0, 0, 0, 0, 0, _a_),
       _az_ = [0, caml_call3(Eliom_content[3][1][351], 0, _ay_, 0), 0],
       _aA_ = caml_call1(Eliom_content[3][1][222], cst_h42n42),
       _aB_ = caml_call2(Eliom_content[3][1][226], 0, _aA_),
       _aC_ = caml_call3(Eliom_content[3][1][224], 0, _aB_, _az_),
       _aD_ = caml_call3(Eliom_content[3][1][223], 0, _aC_, _aw_);
      return caml_call1(Lwt[4], _aD_);
     });
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   var
    equal = runtime.caml_equal,
    hash = Stdlib_Hashtbl[28],
    Cell = [0, equal, hash],
    Grid = caml_call1(Stdlib_Hashtbl[26], Cell),
    _b_ = [0, -1, [0, 0, [0, 1, 0]]],
    _c_ = [0, -1, [0, 0, [0, 1, 0]]],
    _d_ = [0, 0., 0.],
    _e_ = [0, 0., 0.],
    _f_ = [0, 0., 0.],
    _g_ =
      [0,
       [4, 0, [0, 2, 2], 0, [12, 58, [4, 0, [0, 2, 2], 0, 0]]],
       "%02d:%02d"],
    cst_TIME = "TIME ",
    _h_ =
      [0,
       [8, [0, 0, 0], 0, [0, 0], [11, cst_px_Press_Start_2P, 0]],
       cst_0fpx_Press_Start_2P],
    cst_Healed_Creets = "Healed Creets: ",
    _i_ =
      [0,
       [8, [0, 0, 0], 0, [0, 0], [11, cst_px_Press_Start_2P, 0]],
       cst_0fpx_Press_Start_2P],
    cst_px = cst_px$1,
    cst_px$0 = cst_px$1,
    cst_Failed_to_load_image = "Failed to load image: ",
    cst_css_healthyCreet_png = "/css/healthyCreet.png",
    cst_css_sickCreet_png = "/css/sickCreet.png",
    cst_css_meanCreet_png = "/css/meanCreet.png",
    cst_css_berserkCreet_png = "/css/berserkCreet.png",
    cst_css_gameOver_jpg = "/css/gameOver.jpg",
    cst_css_menu_jpg = "/css/menu.jpg",
    cst_Prev = "Prev : ",
    _j_ = [0, 0., 0.],
    cst_draw_zone$0 = cst_draw_zone$1,
    _k_ = [0, 0., 0.],
    _l_ = [0, 0., 0.];
   function generateRandomDirection(param){
    var a = caml_call1(Stdlib_Random[14], 2. * Stdlib_Float[11]);
    return [0, Math.cos(a), Math.sin(a)];
   }
   function clamp(v, min, max){
    var _as_ = caml_call2(Stdlib_Float[23], max, v);
    return caml_call2(Stdlib_Float[24], min, _as_);
   }
   function neighborCells(param){
    var cy = param[2], cx = param[1];
    return caml_call1
            (caml_call1
              (Stdlib_List[24],
               function(dx){
                return caml_call1
                        (caml_call1
                          (Stdlib_List[20],
                           function(dy){return [0, cx + dx | 0, cy + dy | 0];}),
                         _c_);
               }),
             _b_);
   }
   function cellFromPos(param, data){
    var y = param[2], x = param[1];
    return [0, x / (data[9] * 2.) | 0, y / (data[9] * 2.) | 0];
   }
   function creetDistance(_ar_, param){
    var
     y2 = param[2],
     x2 = param[1],
     y1 = _ar_[2],
     x1 = _ar_[1],
     x = y2 - y1,
     x$0 = x2 - x1;
    return x$0 * x$0 + x * x;
   }
   function creetThread(creet, data){
    var ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js[1], data[3]);
    return caml_call3
            (Lwt[81],
             function(exn){
              try{throw caml_maybe_attach_backtrace(exn, 0);}
              catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
             },
             ppx_lwt_0,
             function(param$0){
              if(! data[1]) return Lwt[36];
              var
               t6 = data[2],
               wHeight = t6.height,
               t7 = data[2],
               wWidth = t7.width;
              if(caml_call1(Stdlib_Random[14], 1.) < 0.002)
               creet[3] = generateRandomDirection(0);
              var match$4 = creet[2], y$1 = match$4[2], x$1 = match$4[1];
              if(data[11] === creet[1]){
               var
                match$5 = data[13],
                my = match$5[2],
                mx = match$5[1],
                match$6 = data[12],
                vy = match$6[2],
                vx = match$6[1];
               creet[2] = [0, mx + vx, my + vy];
              }
              else{
               var _ao_ = creet[5];
               if(_ao_)
                if(3 <= _ao_){
                 var
                  match$2 = cellFromPos(creet[2], data),
                  cy = match$2[2],
                  cx = match$2[1],
                  _aj_ = neighborCells([0, cx, cy]),
                  _ak_ = caml_call1(Grid[8], data[10]),
                  _al_ = caml_call1(caml_call1(Stdlib_List[23], _ak_), _aj_),
                  _am_ = caml_call1(Stdlib_List[14], _al_),
                  _an_ =
                    caml_call1
                     (caml_call1
                       (Stdlib_List[44], function(c){return 0 === c[5] ? 1 : 0;}),
                      _am_),
                  match$3 =
                    caml_call1
                     (caml_call2
                       (Stdlib_List[26],
                        function(acc, other){
                         if(! acc) return [0, other];
                         var best = acc[1], _aq_ = creetDistance(creet[2], best[2]);
                         return creetDistance(creet[2], other[2]) < _aq_
                                 ? [0, other]
                                 : acc;
                        },
                        0),
                      _an_);
                 if(match$3){
                  var
                   target = match$3[1],
                   param = target[2],
                   _ap_ = creet[2],
                   y2 = param[2],
                   x2 = param[1],
                   y1 = _ap_[2],
                   x1 = _ap_[1],
                   dx$1 = x2 - x1,
                   dy$1 = y2 - y1,
                   len = Math.sqrt(dx$1 * dx$1 + dy$1 * dy$1),
                   match$7 = len === 0. ? _d_ : [0, dx$1 / len, dy$1 / len],
                   dy$2 = match$7[2],
                   dx$2 = match$7[1];
                  creet[3] = [0, dx$2, dy$2];
                  creet[2] = [0, x$1 + dx$2 * creet[4], y$1 + dy$2 * creet[4]];
                 }
                 else{
                  var
                   match$8 = creet[3],
                   dy$3 = match$8[2],
                   dx$3 = match$8[1];
                  creet[2] =
                   [0,
                    x$1 + dx$3 * (creet[4] * 0.85),
                    y$1 + dy$3 * (creet[4] * 0.85)];
                 }
                }
                else{
                 var match$9 = creet[3], dy$4 = match$9[2], dx$4 = match$9[1];
                 creet[2] =
                  [0,
                   x$1 + dx$4 * (creet[4] * 0.85),
                   y$1 + dy$4 * (creet[4] * 0.85)];
                }
               else{
                var
                 match$10 = creet[3],
                 dy$5 = match$10[2],
                 dx$5 = match$10[1];
                creet[2] = [0, x$1 + dx$5 * creet[4], y$1 + dy$5 * creet[4]];
               }
              }
              var
               match$0 = creet[2],
               y$0 = match$0[2],
               x$0 = match$0[1],
               match$1 = creet[3],
               dy = match$1[2],
               dx = match$1[1],
               r$0 = creet[6];
              a:
              {
               if(! (x$0 - r$0 <= 0.) && ! (wWidth <= x$0 + r$0)){var dx$0 = dx; break a;}
               var dx$0 = - dx;
              }
              a:
              {
               if(! (y$0 - r$0 <= 0.) && ! (wHeight <= y$0 + r$0)){var dy$0 = dy; break a;}
               var dy$0 = - dy;
              }
              creet[3] = [0, dx$0, dy$0];
              var
               match = creet[2],
               y = match[2],
               x = match[1],
               r = creet[6],
               _ai_ = clamp(y, r, wHeight - r);
              creet[2] = [0, clamp(x, r, wWidth - r), _ai_];
              return creetThread(creet, data);
             });
   }
   function rebuildGrid(data){
    data[10] = caml_call1(Grid[1], 1024);
    return caml_call2
            (Stdlib_List[18],
             function(crt){
              var
               cell = cellFromPos(crt[2], data),
               match = caml_call2(Grid[8], data[10], cell);
              if(match) var l = match[1], lst = l; else var lst = 0;
              return caml_call3(Grid[10], data[10], cell, [0, crt, lst]);
             },
             data[4]);
   }
   function contaminate(data, baseProbability, creet){
    if(creet[1] === data[11]) return 0;
    var cy = creet[2][2], t8 = data[2];
    if(cy - creet[6] < t8.height * 0.2) return 0;
    if(baseProbability < caml_call1(Stdlib_Random[14], 1.)) return 0;
    if(creet[5]) return 0;
    creet[5] = 1;
    var _af_ = caml_call1(Stdlib_Random[14], 1.) < 0.5 ? 1 : 0;
    if(_af_){
     if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 2; return 0;}
     if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 3; return 0;}
     var _ag_ = caml_call1(Stdlib_Random[14], 1.) < 0.1 ? 1 : 0;
     if(_ag_){
      if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 3; return 0;}
      if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 2; return 0;}
      var _ah_ = 0;
     }
     else
      var _ah_ = _ag_;
    }
    else
     var _ah_ = _af_;
    return _ah_;
   }
   function resetGrab(data){
    data[19] = data[19] + 1 | 0;
    var
     grabbedCreet =
       caml_call2
        (Stdlib_List[40],
         function(creet){return creet[1] === data[11] ? 1 : 0;},
         data[4]);
    if(! grabbedCreet){data[11] = -1; data[12] = _f_; return;}
    var
     crt = grabbedCreet[1],
     match = crt[2],
     cy = match[2],
     cx = match[1],
     t9 = data[2],
     wHeight = t9.height,
     t10 = data[2],
     wWidth = t10.width,
     h = wHeight * 0.25,
     w = wWidth * 0.5,
     x = wWidth * 0.25,
     _ab_ = x <= cx ? 1 : 0;
    if(_ab_){
     var _ac_ = cx <= x + w ? 1 : 0;
     if(_ac_)
      var _ad_ = 0. <= cy ? 1 : 0, _ae_ = _ad_ ? cy <= 0. + h ? 1 : 0 : _ad_;
     else
      var _ae_ = _ac_;
    }
    else
     var _ae_ = _ab_;
    if(_ae_){if(0 !== crt[5]) data[21] = data[21] + 1 | 0; crt[5] = 0;}
    data[11] = -1;
    data[12] = _e_;
   }
   function updateFullCanvas(data, sprite){
    var
     t11 = data[2],
     wHeight = t11.height,
     t12 = data[2],
     wWidth = t12.width,
     t17 = data[6];
    t17.clearRect(0., 0., wWidth, wHeight);
    var t23 = data[6];
    t23.drawImage(sprite, 0., 0., wWidth, wHeight);
    return caml_call1(Lwt[4], 0);
   }
   function drawTimer(ctx, data){
    var
     t24 = Js_of_ocaml_Js[26],
     now = new t24,
     t26 = data[20],
     _$_ = t26.getTime(),
     ms = now.getTime() - _$_,
     elapsed = ms / 1000. | 0,
     m = elapsed / 60 | 0,
     s = elapsed % 60 | 0,
     _aa_ = caml_call3(Stdlib_Printf[4], _g_, m, s),
     txt = caml_call2(Stdlib[28], cst_TIME, _aa_),
     t27 =
       caml_jsstring_of_string
        (caml_call2(Stdlib_Printf[4], _h_, 16. * data[5]));
    ctx.font = t27;
    ctx.fillStyle = cst_white;
    var
     t34 = 30. * data[5],
     t31 = data[2],
     t33 = t31.width - 200. * data[5],
     t32 = caml_jsstring_of_string(txt);
    ctx.fillText(t32, t33, t34);
   }
   function drawScore(ctx, data){
    var
     ___ = caml_call1(Stdlib[33], data[21]),
     txt = caml_call2(Stdlib[28], cst_Healed_Creets, ___),
     t36 =
       caml_jsstring_of_string
        (caml_call2(Stdlib_Printf[4], _i_, 16. * data[5]));
    ctx.font = t36;
    ctx.fillStyle = cst_white;
    var
     t42 = 30. * data[5],
     t41 = 20. * data[5],
     t40 = caml_jsstring_of_string(txt);
    ctx.fillText(t40, t41, t42);
   }
   function gameIteration(data){
    var ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js[1], data[3]);
    return caml_call3
            (Lwt[81],
             function(exn){
              try{throw caml_maybe_attach_backtrace(exn, 0);}
              catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
             },
             ppx_lwt_0,
             function(param){
              var
               t44 = data[2],
               wHeight = t44.height,
               t45 = data[2],
               wWidth = t45.width;
              if(data[1]){
               data[7] = data[7] * 1.0001;
               rebuildGrid(data);
               var t50 = data[6];
               t50.clearRect(0., 0., wWidth, wHeight);
               caml_call2
                (Stdlib_List[18],
                 function(creet){
                  var match = data[14];
                  if(! match) return 0;
                  var sprites = match[1];
                  switch(creet[5]){
                    case 0:
                     var img = sprites[1]; break;
                    case 1:
                     var img = sprites[2]; break;
                    case 2:
                     var img = sprites[4]; break;
                    default: var img = sprites[3];
                  }
                  var
                   ctx = data[6],
                   match$0 = creet[2],
                   y = match$0[2],
                   x = match$0[1],
                   size = creet[6] * 2.,
                   t2 = y - creet[6],
                   t1 = x - creet[6];
                  return ctx.drawImage(img, t1, t2, size, size);
                 },
                 data[4]);
               drawTimer(data[6], data);
               drawScore(data[6], data);
               var toContaminate = [0, 0];
               caml_call2
                (Stdlib_List[18],
                 function(creet){
                  creet[4] = data[7];
                  var cy$0 = creet[2][2], status = creet[5];
                  if(status){
                   var
                    grid = data[10],
                    match = cellFromPos(creet[2], data),
                    cy = match[2],
                    cx = match[1],
                    _U_ = neighborCells([0, cx, cy]),
                    _V_ = caml_call1(Grid[8], grid),
                    _W_ = caml_call1(caml_call1(Stdlib_List[23], _V_), _U_),
                    _X_ = caml_call1(Stdlib_List[14], _W_),
                    overlap =
                      caml_call1
                       (caml_call1
                         (Stdlib_List[44],
                          function(other){
                           var _Z_ = other[1] !== creet[1] ? 1 : 0;
                           if(! _Z_) return _Z_;
                           var
                            match = creet[2],
                            y1 = match[2],
                            x1 = match[1],
                            match$0 = other[2],
                            y2 = match$0[2],
                            x2 = match$0[1],
                            dx = x1 - x2,
                            dy = y1 - y2,
                            r = creet[6] + other[6];
                           return dx * dx + dy * dy <= r * r ? 1 : 0;
                          }),
                        _X_);
                   caml_call2
                    (Stdlib_List[18],
                     function(other){
                      toContaminate[1] = [0, other, toContaminate[1]];
                      return 0;
                     },
                     overlap);
                   return 2 === status
                           ? (creet
                              [6]
                             = clamp(creet[6] + 0.005 * creet[6], data[8], data[9]),
                             0)
                           : 3
                             === status
                             ? (creet
                                [6]
                               =
                                clamp(creet[6] - 0.005 * creet[6], data[8] * 0.85, data[9]),
                               0)
                             : (creet
                                [6]
                               = clamp(creet[6] - 0.005 * creet[6], data[8], data[9]),
                               0);
                  }
                  creet[6] =
                   creet[6] < data[8]
                    ? clamp(creet[6] + 0.005 * creet[6], creet[6], data[8])
                    : clamp(creet[6] - 0.005 * creet[6], data[8], data[9]);
                  var _Y_ = wHeight * 0.85 < cy$0 + creet[6] ? 1 : 0;
                  return _Y_ ? contaminate(data, 1., creet) : _Y_;
                 },
                 data[4]);
               var _S_ = 0.02;
               caml_call2
                (Stdlib_List[18],
                 function(_T_){return contaminate(data, _S_, _T_);},
                 toContaminate[1]);
               data[1] =
                caml_call2
                 (Stdlib_List[34],
                  function(c){return 0 === c[5] ? 1 : 0;},
                  data[4]);
               return gameIteration(data);
              }
              var match = data[14];
              if(! match) return caml_call1(Lwt[4], 0);
              var spr = match[1];
              updateFullCanvas(data, spr[5]);
              drawTimer(data[6], data);
              drawScore(data[6], data);
              return caml_call1(Lwt[4], 0);
             });
   }
   function mousePositionOnCanvas(event, data){
    var
     canvas = data[2],
     rect = canvas.getBoundingClientRect(),
     mx = event.clientX - rect.left,
     my = event.clientY - rect.top;
    return [0, mx, my];
   }
   function generateCreet(id, speed, base_radius, canvas){
    var
     _R_ = generateRandomDirection(0),
     newCreet =
       [0,
        id,
        [0, canvas.width / 2., canvas.height / 2.],
        _R_,
        speed,
        0,
        base_radius];
    return newCreet;
   }
   function updateCanvasSize(canvas){
    var
     t58 = Js_of_ocaml_Dom_html[8],
     inner_w = t58.innerWidth,
     t59 = Js_of_ocaml_Dom_html[8],
     inner_h = t59.innerHeight,
     scale = caml_call2(Stdlib_Float[23], inner_w / 1920., inner_h / 1080.),
     t60 = 1920. * scale | 0;
    canvas.width = t60;
    var t62 = 1080. * scale | 0;
    canvas.height = t62;
    var t66 = canvas.style;
    t66.position = "absolute";
    var
     left = ((inner_w | 0) - canvas.width | 0) / 2 | 0,
     top = ((inner_h | 0) - canvas.height | 0) / 2 | 0,
     _P_ = caml_call1(Stdlib[33], left),
     t70 = caml_jsstring_of_string(caml_call2(Stdlib[28], _P_, cst_px)),
     t71 = canvas.style;
    t71.left = t70;
    var
     _Q_ = caml_call1(Stdlib[33], top),
     t73 = caml_jsstring_of_string(caml_call2(Stdlib[28], _Q_, cst_px$0)),
     t74 = canvas.style;
    t74.top = t73;
    return scale;
   }
   function loadImage(src){
    var
     img = caml_call1(Js_of_ocaml_Dom_html[68], Js_of_ocaml_Dom_html[2]),
     match = caml_call1(Lwt[1], 0),
     wakener = match[2],
     promise = match[1],
     t75 =
       caml_call1
        (Js_of_ocaml_Dom[10],
         function(param){
          caml_call2(Lwt[52], wakener, img);
          return Js_of_ocaml_Js[8];
         });
    img.onload = t75;
    var
     t77 =
       caml_call1
        (Js_of_ocaml_Dom[10],
         function(param){
          var _O_ = caml_call2(Stdlib[28], cst_Failed_to_load_image, src);
          caml_call1(Lwt[44], _O_);
          return Js_of_ocaml_Js[8];
         });
    img.onerror = t77;
    var t79 = caml_jsstring_of_string(src);
    img.src = t79;
    return promise;
   }
   function generateDataInitalCreets(data){
    var canvas = data[2];
    data[4] = 0;
    var _J_ = data[4];
    data[4] =
     [0, generateCreet(0, 4. * data[5], data[8] * data[5], canvas), _J_];
    var _K_ = data[4];
    data[4] =
     [0, generateCreet(1, 4. * data[5], data[8] * data[5], canvas), _K_];
    var _L_ = data[4];
    data[4] =
     [0, generateCreet(2, 4. * data[5], data[8] * data[5], canvas), _L_];
    var _M_ = data[4];
    data[4] =
     [0, generateCreet(3, 4. * data[5], data[8] * data[5], canvas), _M_];
    var _N_ = data[4];
    data[4] =
     [0, generateCreet(4, 4. * data[5], data[8] * data[5], canvas), _N_];
   }
   function tryLoadingSprites(onReady, data, iterations){
    if(3 < iterations) return Lwt[36];
    var match = data[14];
    if(match){var sprites = match[1]; return caml_call1(onReady, sprites);}
    var
     healthyCreetP = loadImage(cst_css_healthyCreet_png),
     sickCreetP = loadImage(cst_css_sickCreet_png),
     meanCreetP = loadImage(cst_css_meanCreet_png),
     berserkCreetP = loadImage(cst_css_berserkCreet_png),
     gameOverBackP = loadImage(cst_css_gameOver_jpg),
     menuBackP = loadImage(cst_css_menu_jpg),
     ppx_lwt_0 =
       caml_call3
        (Lwt[81],
         function(exn){
          try{throw caml_maybe_attach_backtrace(exn, 0);}
          catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
         },
         gameOverBackP,
         function(gameOverB){
          return caml_call3
                  (Lwt[81],
                   function(exn){
                    try{throw caml_maybe_attach_backtrace(exn, 0);}
                    catch(exn){
                     var exn$0 = caml_wrap_exception(exn);
                     return exn$0;
                    }
                   },
                   healthyCreetP,
                   function(healthy){
                    return caml_call3
                            (Lwt[81],
                             function(exn){
                              try{throw caml_maybe_attach_backtrace(exn, 0);}
                              catch(exn){
                               var exn$0 = caml_wrap_exception(exn);
                               return exn$0;
                              }
                             },
                             sickCreetP,
                             function(sick){
                              return caml_call3
                                      (Lwt[81],
                                       function(exn){
                                        try{throw caml_maybe_attach_backtrace(exn, 0);}
                                        catch(exn){
                                         var exn$0 = caml_wrap_exception(exn);
                                         return exn$0;
                                        }
                                       },
                                       berserkCreetP,
                                       function(berserk){
                                        return caml_call3
                                                (Lwt[81],
                                                 function(exn){
                                                  try{throw caml_maybe_attach_backtrace(exn, 0);}
                                                  catch(exn){
                                                   var exn$0 = caml_wrap_exception(exn);
                                                   return exn$0;
                                                  }
                                                 },
                                                 meanCreetP,
                                                 function(mean){
                                                  return caml_call3
                                                          (Lwt[81],
                                                           function(exn){
                                                            try{throw caml_maybe_attach_backtrace(exn, 0);}
                                                            catch(exn){
                                                             var exn$0 = caml_wrap_exception(exn);
                                                             return exn$0;
                                                            }
                                                           },
                                                           menuBackP,
                                                           function(menuB){
                                                            data[14] =
                                                             [0, [0, healthy, sick, mean, berserk, gameOverB, menuB]];
                                                            return Lwt[36];
                                                           });
                                                 });
                                       });
                             });
                   });
         });
    return caml_call3
            (Lwt[81],
             function(exn){
              try{throw caml_maybe_attach_backtrace(exn, 0);}
              catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
             },
             ppx_lwt_0,
             function(param){
              return tryLoadingSprites(onReady, data, iterations + 1 | 0);
             });
   }
   function duplicateCreet(data, healthyCreets, index){
    var creetOpt = caml_call2(Stdlib_List[9], healthyCreets, index);
    if(! creetOpt) return;
    var
     crt = creetOpt[1],
     _E_ = crt[6],
     _F_ = crt[5],
     _G_ = crt[4],
     _H_ = generateRandomDirection(0),
     _I_ = crt[2],
     newCreet =
       [0, caml_call1(Stdlib_List[1], data[4]), _I_, _H_, _G_, _F_, _E_];
    data[4] = [0, newCreet, data[4]];
    return caml_call1
            (Lwt[11], function(param){return creetThread(newCreet, data);});
   }
   function reproduceCreet(data){
    var
     prevId = data[18],
     ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js[1], 10.);
    return caml_call3
            (Lwt[81],
             function(exn){
              try{throw caml_maybe_attach_backtrace(exn, 0);}
              catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
             },
             ppx_lwt_0,
             function(param){
              if(data[18] === prevId && data[1]){
               var _C_ = data[17];
               if(caml_call1(Stdlib_List[1], data[4]) < _C_){
                var
                 healthyCreets =
                   caml_call2
                    (Stdlib_List[44],
                     function(creet){return 0 === creet[5] ? 1 : 0;},
                     data[4]),
                 creetQuantity = caml_call1(Stdlib_List[1], healthyCreets);
                if(1 === creetQuantity)
                 duplicateCreet(data, healthyCreets, 0);
                else{
                 var
                  _D_ = caml_call1(Stdlib[33], creetQuantity),
                  t88 =
                    caml_jsstring_of_string
                     (caml_call2(Stdlib[28], cst_Prev, _D_)),
                  t89 = Js_of_ocaml_Firebug[1];
                 t89.log(t88);
                 duplicateCreet
                  (data,
                   healthyCreets,
                   caml_call1(Stdlib_Random[5], creetQuantity - 1 | 0));
                }
                return reproduceCreet(data);
               }
              }
              return Lwt[36];
             });
   }
   function restartGame(data){
    data[1] = 1;
    data[11] = -1;
    var t90 = Js_of_ocaml_Js[26];
    data[20] = new t90;
    var
     t91 = data[20],
     _A_ = t91.getTime(),
     _B_ = caml_call1(Stdlib[35], _A_),
     t92 = caml_jsstring_of_string(caml_call2(Stdlib[28], cst, _B_)),
     t93 = Js_of_ocaml_Firebug[1];
    t93.log(t92);
    data[12] = _j_;
    data[18] = data[18] + 1 | 0;
    data[7] = 4. * data[5];
    generateDataInitalCreets(data);
    rebuildGrid(data);
    data[21] = 0;
    caml_call2
     (Stdlib_List[18],
      function(creet){
       return caml_call1
               (Lwt[11], function(param){return creetThread(creet, data);});
      },
      data[4]);
    caml_call1(Lwt[11], function(param){return reproduceCreet(data);});
    return caml_call1
            (Lwt[11],
             function(param){
              return tryLoadingSprites
                      (function(sprites){return gameIteration(data);}, data, 0);
             });
   }
   caml_call1
    (Lwt[11],
     function(param){
      var ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js_events[147], 0);
      return caml_call3
              (Lwt[81],
               function(exn){
                try{throw caml_maybe_attach_backtrace(exn, 0);}
                catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;
                }
               },
               ppx_lwt_0,
               function(param){
                caml_call1(Stdlib_Random[3], 0);
                var
                 doc = Js_of_ocaml_Dom_html[2],
                 match = caml_call1(Js_of_ocaml_Dom_html[3], cst_draw_zone$0);
                if(match){
                 var
                  div = match[1],
                  canvas = caml_call1(Js_of_ocaml_Dom_html[111], doc);
                 canvas.id = "canvas";
                 var baseScale = updateCanvasSize(canvas);
                 caml_call2(Js_of_ocaml_Dom[5], div, canvas);
                 var
                  t98 = Js_of_ocaml_Dom_html[1],
                  ctx = canvas.getContext(t98),
                  rad = 40. * baseScale,
                  t100 = Js_of_ocaml_Js[26],
                  _m_ = new t100,
                  data =
                    [0,
                     0,
                     canvas,
                     0.016,
                     0,
                     baseScale,
                     ctx,
                     4.,
                     rad,
                     rad * 4.,
                     caml_call1(Grid[1], 1024),
                     -1,
                     _l_,
                     _k_,
                     0,
                     1,
                     0,
                     10,
                     0,
                     0,
                     _m_,
                     0];
                 generateDataInitalCreets(data);
                 rebuildGrid(data);
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return tryLoadingSprites
                            (function(sprites){
                              return updateFullCanvas(data, sprites[6]);
                             },
                             data,
                             0);
                   });
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return caml_call5
                            (Js_of_ocaml_lwt_Lwt_js_events[88],
                             0,
                             0,
                             0,
                             Js_of_ocaml_Dom_html[8],
                             function(t101, stop){
                              var match = caml_call1(Js_of_ocaml_Js[6][10], t101.key);
                              if(! match) return Lwt[36];
                              var
                               key = match[1],
                               key$0 = runtime.caml_string_of_jsstring(key);
                              a:
                              {
                               if(key$0 !== "r" && key$0 !== "R"){
                                if(key$0 !== "p" && key$0 !== "P"){
                                 var
                                  _y_ = key$0 === "m" ? 1 : 0,
                                  _z_ = _y_ || (key$0 === "M" ? 1 : 0);
                                 if(! _z_) break a;
                                 var match$0 = data[16];
                                 if(match$0){
                                  var t102 = match$0[1], t103 = ! ! (1 - (t102.muted | 0));
                                  t102.muted = t103;
                                 }
                                 break a;
                                }
                                if(! data[15]) break a;
                                var
                                 audio =
                                   caml_call1
                                    (Js_of_ocaml_Dom_html[108], Js_of_ocaml_Dom_html[2]);
                                audio.src = "/css/music.mp3";
                                var t83 = Js_of_ocaml_Js[7];
                                audio.loop = t83;
                                audio.volume = 0.5;
                                audio.play();
                                data[16] = [0, audio];
                                data[15] = 0;
                                restartGame(data);
                                break a;
                               }
                               var _w_ = 1 - data[1], _x_ = _w_ ? 1 - data[15] : _w_;
                               if(_x_) restartGame(data);
                              }
                              return Lwt[36];
                             });
                   });
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return caml_call5
                            (Js_of_ocaml_lwt_Lwt_js_events[82],
                             0,
                             0,
                             0,
                             data[2],
                             function(ev, stop){
                              if(! data[1]) return Lwt[36];
                              rebuildGrid(data);
                              var
                               mousePos = mousePositionOnCanvas(ev, data),
                               grid = data[10],
                               my = mousePos[2],
                               mx = mousePos[1],
                               match = cellFromPos([0, mx, my], data),
                               cy = match[2],
                               cx = match[1],
                               _p_ = neighborCells([0, cx, cy]),
                               _q_ = caml_call1(Grid[8], grid),
                               _r_ = caml_call1(caml_call1(Stdlib_List[23], _q_), _p_),
                               _s_ = caml_call1(Stdlib_List[14], _r_),
                               _t_ =
                                 caml_call1
                                  (caml_call1
                                    (Stdlib_List[44],
                                     function(creet){
                                      var
                                       match = creet[2],
                                       y = match[2],
                                       x = match[1],
                                       dx = mx - x,
                                       dy = my - y,
                                       rad = creet[6] + 5. * data[5];
                                      return dx * dx + dy * dy <= rad * rad ? 1 : 0;
                                     }),
                                   _s_),
                               param =
                                 caml_call1
                                  (caml_call1
                                    (Stdlib_List[59],
                                     function(a, b){return runtime.caml_int_compare(b[1], a[1]);}),
                                   _t_);
                              if(param)
                               var x = param[1], match$0 = [0, x];
                              else
                               var match$0 = 0;
                              if(! match$0) return Lwt[36];
                              var c = match$0[1];
                              data[11] = c[1];
                              var
                               my$0 = mousePos[2],
                               mx$0 = mousePos[1],
                               match$1 = c[2],
                               cy$0 = match$1[2],
                               cx$0 = match$1[1];
                              data[12] = [0, cx$0 - mx$0, cy$0 - my$0];
                              data[19] = data[19] + 1 | 0;
                              var tempToken = data[19];
                              c[3] = generateRandomDirection(0);
                              caml_call1
                               (Lwt[11],
                                function(param){
                                 var ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js[1], 3.);
                                 return caml_call3
                                         (Lwt[81],
                                          function(exn){
                                           try{throw caml_maybe_attach_backtrace(exn, 0);}
                                           catch(exn){
                                            var exn$0 = caml_wrap_exception(exn);
                                            return exn$0;
                                           }
                                          },
                                          ppx_lwt_0,
                                          function(param){
                                           var
                                            _u_ = data[19] === tempToken ? 1 : 0,
                                            _v_ = _u_ ? data[11] === c[1] ? 1 : 0 : _u_;
                                           if(_v_) resetGrab(data);
                                           return Lwt[36];
                                          });
                                });
                              return Lwt[36];
                             });
                   });
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return caml_call5
                            (Js_of_ocaml_lwt_Lwt_js_events[83],
                             0,
                             0,
                             0,
                             data[2],
                             function(param, stop){resetGrab(data); return Lwt[36];});
                   });
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return caml_call5
                            (Js_of_ocaml_lwt_Lwt_js_events[86],
                             0,
                             0,
                             0,
                             data[2],
                             function(param, stop){resetGrab(data); return Lwt[36];});
                   });
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return caml_call5
                            (Js_of_ocaml_lwt_Lwt_js_events[85],
                             0,
                             0,
                             0,
                             data[2],
                             function(ev, stop){
                              data[13] = mousePositionOnCanvas(ev, data);
                              return Lwt[36];
                             });
                   });
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return caml_call1
                            (Js_of_ocaml_lwt_Lwt_js_events[156],
                             function(param, stop){
                              var previousScale = data[5];
                              data[5] = updateCanvasSize(canvas);
                              var ratio = data[5] / previousScale;
                              data[8] = data[8] * ratio;
                              data[9] = data[8] * 4.;
                              data[7] = data[7] * ratio;
                              caml_call2
                               (Stdlib_List[18],
                                function(creet){
                                 creet[4] = data[7];
                                 var match = creet[2], y = match[2], x = match[1];
                                 creet[2] = [0, x * ratio, y * ratio];
                                 creet[6] = creet[6] * ratio;
                                 return 0;
                                },
                                data[4]);
                              if(data[15])
                               caml_call1
                                (Lwt[11],
                                 function(param){
                                  return tryLoadingSprites
                                          (function(sprites){
                                            updateFullCanvas(data, sprites[6]);
                                            drawTimer(data[6], data);
                                            drawScore(data[6], data);
                                            return Lwt[36];
                                           },
                                           data,
                                           0);
                                 });
                              else{
                               var _n_ = 1 - data[1], _o_ = _n_ ? 1 - data[15] : _n_;
                               if(_o_)
                                caml_call1
                                 (Lwt[11],
                                  function(param){
                                   return tryLoadingSprites
                                           (function(sprites){
                                             updateFullCanvas(data, sprites[5]);
                                             drawTimer(data[6], data);
                                             drawScore(data[6], data);
                                             return Lwt[36];
                                            },
                                            data,
                                            0);
                                  });
                              }
                              return Lwt[36];
                             });
                   });
                 return Lwt[36];
                }
                var t95 = Js_of_ocaml_Firebug[1];
                t95.log("Div not found");
                return Lwt[36];
               });
     });
   var H42n42 = [0];
   runtime.caml_register_global(193, H42n42, "H42n42");
   return;
  }
  (globalThis));
