// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cmo, use-js-string=true, version=5.9.1

//# unitInfo: Provides: H42n42
//# unitInfo: Requires: Eliom_client, Eliom_client_core, Eliom_content, Eliom_registration, Eliom_service, Js_of_ocaml__Dom, Js_of_ocaml__Dom_html, Js_of_ocaml__Firebug, Js_of_ocaml__Js, Js_of_ocaml_lwt__Lwt_js, Lwt, Stdlib, Stdlib__Float, Stdlib__Hashtbl, Stdlib__List, Stdlib__Random
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    cst_P = "P",
    cst_draw_zone$1 = "draw-zone",
    cst_h42n42_eliom = "h42n42.eliom",
    cst_px$1 = "px",
    caml_jsstring_of_string = runtime.caml_jsstring_of_string,
    caml_maybe_attach_backtrace = runtime.caml_maybe_attach_backtrace,
    caml_wrap_exception = runtime.caml_wrap_exception;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) === 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) === 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   function caml_call3(f, a0, a1, a2){
    return (f.l >= 0 ? f.l : f.l = f.length) === 3
            ? f(a0, a1, a2)
            : runtime.caml_call_gen(f, [a0, a1, a2]);
   }
   function caml_call10(f, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9){
    return (f.l >= 0 ? f.l : f.l = f.length) === 10
            ? f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9)
            : runtime.caml_call_gen
              (f, [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9]);
   }
   function caml_call11(f, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10){
    return (f.l >= 0 ? f.l : f.l = f.length) === 11
            ? f(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10)
            : runtime.caml_call_gen
              (f, [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10]);
   }
   var
    dummy = 0,
    global_data = runtime.caml_get_global_data(),
    eliom_compilation_unit_id_eZ0b = "eZ0bjX",
    global_data_path = [0, [0, "__global_data__", 0]],
    Stdlib_List = global_data.Stdlib__List,
    Lwt = global_data.Lwt,
    Js_of_ocaml_lwt_Lwt_js = global_data.Js_of_ocaml_lwt__Lwt_js,
    Stdlib = global_data.Stdlib,
    Js_of_ocaml_Firebug = global_data.Js_of_ocaml__Firebug,
    Stdlib_Random = global_data.Stdlib__Random,
    Js_of_ocaml_Js = global_data.Js_of_ocaml__Js,
    Js_of_ocaml_Dom_html = global_data.Js_of_ocaml__Dom_html,
    Js_of_ocaml_Dom = global_data.Js_of_ocaml__Dom,
    Stdlib_Float = global_data.Stdlib__Float,
    Eliom_content = global_data.Eliom_content,
    Eliom_service = global_data.Eliom_service,
    Eliom_client = global_data.Eliom_client,
    Eliom_registration = global_data.Eliom_registration,
    Eliom_client_core = global_data.Eliom_client_core,
    Stdlib_Hashtbl = global_data.Stdlib__Hashtbl,
    application_name = caml_call1(Eliom_client[18], 0),
    App =
      caml_call1
       (Eliom_registration[4], [0, application_name, global_data_path]);
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   caml_call1(Eliom_client[19], 0);
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   caml_call1(Eliom_client_core[56][2], eliom_compilation_unit_id_eZ0b);
   var
    main_service =
      caml_call3
       (Eliom_client_core[56][5],
        [0, "main_service"],
        [0,
         [0,
          [0, cst_h42n42_eliom, 24, 889, 917],
          [0, cst_h42n42_eliom, 24, 889, 917]]],
        "eZ0bjX1"),
    cst_draw_zone = cst_draw_zone$1,
    _a_ = [0, "css", [0, "h42n42.css", 0]],
    cst_h42n42 = "h42n42";
   caml_call11
    (App[2],
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     main_service,
     0,
     function(_ad_, param){
      var
       _ae_ = [0, [0, caml_call1(Eliom_content[3][1][8], cst_draw_zone), 0]],
       _af_ = [0, caml_call2(Eliom_content[3][1][248], _ae_, 0), 0],
       _ag_ = caml_call2(Eliom_content[3][1][227], 0, _af_),
       _ah_ = caml_call1(Eliom_service[5], 0),
       _ai_ =
         caml_call10
          (Eliom_content[3][1][349], 0, 0, 0, _ah_, 0, 0, 0, 0, 0, _a_),
       _aj_ = [0, caml_call3(Eliom_content[3][1][351], 0, _ai_, 0), 0],
       _ak_ = caml_call1(Eliom_content[3][1][222], cst_h42n42),
       _al_ = caml_call2(Eliom_content[3][1][226], 0, _ak_),
       _am_ = caml_call3(Eliom_content[3][1][224], 0, _al_, _aj_),
       _an_ = caml_call3(Eliom_content[3][1][223], 0, _am_, _ag_);
      return caml_call1(Lwt[4], _an_);
     });
   caml_call1(Eliom_client_core[56][3], eliom_compilation_unit_id_eZ0b);
   var
    equal = runtime.caml_equal,
    hash = Stdlib_Hashtbl[28],
    Cell = [0, equal, hash],
    Grid = caml_call1(Stdlib_Hashtbl[26], Cell),
    _b_ = [0, -1, [0, 0, [0, 1, 0]]],
    _c_ = [0, -1, [0, 0, [0, 1, 0]]],
    _d_ = [0, 0., 0.],
    _e_ = [0, 0., 0.],
    cst_px = cst_px$1,
    cst_px$0 = cst_px$1,
    cst_Failed_to_load_image = "Failed to load image: ",
    cst_css_healthyCreet_png = "/css/healthyCreet.png",
    cst_css_sickCreet_png = "/css/sickCreet.png",
    cst_css_meanCreet_png = "/css/meanCreet.png",
    cst_css_berserkCreet_png = "/css/berserkCreet.png",
    cst_css_gameOver_png = "/css/gameOver.png",
    cst_css_menu_jpg = "/css/menu.jpg",
    cst_Prev = "Prev : ",
    _f_ = [0, 0., 0.],
    cst_draw_zone$0 = cst_draw_zone$1,
    _g_ = [0, 0., 0.],
    _h_ = [0, 0., 0.];
   function generateRandomDirection(param){
    var a = caml_call1(Stdlib_Random[14], 2. * Stdlib_Float[11]);
    return [0, Math.cos(a), Math.sin(a)];
   }
   function clamp(v, min, max){
    var _ac_ = caml_call2(Stdlib_Float[23], max, v);
    return caml_call2(Stdlib_Float[24], min, _ac_);
   }
   function neighborCells(param){
    var cy = param[2], cx = param[1];
    return caml_call1
            (caml_call1
              (Stdlib_List[24],
               function(dx){
                return caml_call1
                        (caml_call1
                          (Stdlib_List[20],
                           function(dy){return [0, cx + dx | 0, cy + dy | 0];}),
                         _c_);
               }),
             _b_);
   }
   function cellFromPos(param, data){
    var y = param[2], x = param[1];
    return [0, x / (data[9] * 2.) | 0, y / (data[9] * 2.) | 0];
   }
   function creetDistance(_ab_, param){
    var
     y2 = param[2],
     x2 = param[1],
     y1 = _ab_[2],
     x1 = _ab_[1],
     x = y2 - y1,
     x$0 = x2 - x1;
    return x$0 * x$0 + x * x;
   }
   function rebuildGrid(data){
    data[10] = caml_call1(Grid[1], 1024);
    return caml_call2
            (Stdlib_List[18],
             function(crt){
              var
               cell = cellFromPos(crt[2], data),
               match = caml_call2(Grid[8], data[10], cell);
              if(match) var l = match[1], lst = l; else var lst = 0;
              return caml_call3(Grid[10], data[10], cell, [0, crt, lst]);
             },
             data[4]);
   }
   function contaminate(data, baseProbability, creet){
    if(creet[1] === data[11]) return 0;
    var cy = creet[2][2], t6 = data[2];
    if(cy - creet[6] < t6.height * 0.2) return 0;
    if(baseProbability < caml_call1(Stdlib_Random[14], 1.)) return 0;
    if(creet[5]) return 0;
    creet[5] = 1;
    var ___ = caml_call1(Stdlib_Random[14], 1.) < 0.5 ? 1 : 0;
    if(___){
     if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 2; return 0;}
     if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 3; return 0;}
     var _$_ = caml_call1(Stdlib_Random[14], 1.) < 0.1 ? 1 : 0;
     if(_$_){
      if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 3; return 0;}
      if(caml_call1(Stdlib_Random[14], 1.) < 0.1){creet[5] = 2; return 0;}
      var _aa_ = 0;
     }
     else
      var _aa_ = _$_;
    }
    else
     var _aa_ = ___;
    return _aa_;
   }
   function resetGrab(data){
    data[19] = data[19] + 1 | 0;
    data[11] = -1;
    data[12] = _e_;
   }
   function updateFullCanvas(data, sprite){
    var
     t7 = data[2],
     wHeight = t7.height,
     t8 = data[2],
     wWidth = t8.width,
     t13 = data[6];
    t13.clearRect(0., 0., wWidth, wHeight);
    var t19 = data[6];
    t19.drawImage(sprite, 0., 0., wWidth, wHeight);
    return caml_call1(Lwt[4], 0);
   }
   function gameIteration(data){
    var ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js[1], data[3]);
    return caml_call3
            (Lwt[81],
             function(exn){
              try{throw caml_maybe_attach_backtrace(exn, 0);}
              catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
             },
             ppx_lwt_0,
             function(param){
              var
               t20 = data[2],
               wHeight = t20.height,
               t21 = data[2],
               wWidth = t21.width;
              if(data[1]){
               data[7] = data[7] * 1.0002;
               rebuildGrid(data);
               var t26 = data[6];
               t26.clearRect(0., 0., wWidth, wHeight);
               caml_call2
                (Stdlib_List[18],
                 function(creet){
                  if(caml_call1(Stdlib_Random[14], 1.) < 0.002)
                   creet[3] = generateRandomDirection(0);
                  var match$4 = creet[2], y$1 = match$4[2], x$1 = match$4[1];
                  if(data[11] === creet[1]){
                   var
                    match$5 = data[13],
                    my = match$5[2],
                    mx = match$5[1],
                    match$6 = data[12],
                    vy = match$6[2],
                    vx = match$6[1];
                   creet[2] = [0, mx + vx, my + vy];
                  }
                  else if(3 <= creet[5]){
                   var
                    match$2 = cellFromPos(creet[2], data),
                    cy = match$2[2],
                    cx = match$2[1],
                    _T_ = neighborCells([0, cx, cy]),
                    _U_ = caml_call1(Grid[8], data[10]),
                    _V_ = caml_call1(caml_call1(Stdlib_List[23], _U_), _T_),
                    _W_ = caml_call1(Stdlib_List[14], _V_),
                    _X_ =
                      caml_call1
                       (caml_call1
                         (Stdlib_List[44], function(c){return 0 === c[5] ? 1 : 0;}),
                        _W_),
                    match$3 =
                      caml_call1
                       (caml_call2
                         (Stdlib_List[26],
                          function(acc, other){
                           if(! acc) return [0, other];
                           var best = acc[1], _Z_ = creetDistance(creet[2], best[2]);
                           return creetDistance(creet[2], other[2]) < _Z_
                                   ? [0, other]
                                   : acc;
                          },
                          0),
                        _X_);
                   if(match$3){
                    var
                     target = match$3[1],
                     param = target[2],
                     _Y_ = creet[2],
                     y2 = param[2],
                     x2 = param[1],
                     y1 = _Y_[2],
                     x1 = _Y_[1],
                     dx$1 = x2 - x1,
                     dy$1 = y2 - y1,
                     len = Math.sqrt(dx$1 * dx$1 + dy$1 * dy$1),
                     match$7 = len === 0. ? _d_ : [0, dx$1 / len, dy$1 / len],
                     dy$2 = match$7[2],
                     dx$2 = match$7[1];
                    creet[3] = [0, dx$2, dy$2];
                    creet[2] = [0, x$1 + dx$2 * creet[4], y$1 + dy$2 * creet[4]];
                   }
                   else{
                    var
                     match$8 = creet[3],
                     dy$3 = match$8[2],
                     dx$3 = match$8[1];
                    creet[2] = [0, x$1 + dx$3 * creet[4], y$1 + dy$3 * creet[4]];
                   }
                  }
                  else{
                   var
                    match$9 = creet[3],
                    dy$4 = match$9[2],
                    dx$4 = match$9[1];
                   creet[2] = [0, x$1 + dx$4 * creet[4], y$1 + dy$4 * creet[4]];
                  }
                  var
                   match$0 = creet[2],
                   y$0 = match$0[2],
                   x$0 = match$0[1],
                   match$1 = creet[3],
                   dy = match$1[2],
                   dx = match$1[1],
                   r$0 = creet[6];
                  a:
                  {
                   if(! (x$0 - r$0 <= 0.) && ! (wWidth <= x$0 + r$0)){var dx$0 = dx; break a;}
                   var dx$0 = - dx;
                  }
                  a:
                  {
                   if(! (y$0 - r$0 <= 0.) && ! (wHeight <= y$0 + r$0)){var dy$0 = dy; break a;}
                   var dy$0 = - dy;
                  }
                  creet[3] = [0, dx$0, dy$0];
                  var
                   match = creet[2],
                   y = match[2],
                   x = match[1],
                   r = creet[6],
                   _S_ = clamp(y, r, wHeight - r);
                  creet[2] = [0, clamp(x, r, wWidth - r), _S_];
                  var match$10 = data[14];
                  if(! match$10) return 0;
                  var sprites = match$10[1];
                  switch(creet[5]){
                    case 0:
                     var img = sprites[1]; break;
                    case 1:
                     var img = sprites[2]; break;
                    case 2:
                     var img = sprites[4]; break;
                    default: var img = sprites[3];
                  }
                  var
                   ctx = data[6],
                   match$11 = creet[2],
                   y$2 = match$11[2],
                   x$2 = match$11[1],
                   size = creet[6] * 2.,
                   t2 = y$2 - creet[6],
                   t1 = x$2 - creet[6];
                  return ctx.drawImage(img, t1, t2, size, size);
                 },
                 data[4]);
               var toContaminate = [0, 0];
               caml_call2
                (Stdlib_List[18],
                 function(creet){
                  creet[4] = data[7];
                  var cy$0 = creet[2][2], status = creet[5];
                  if(! status){
                   creet[6] =
                    creet[6] < data[8]
                     ? clamp(creet[6] + 0.005 * creet[6], creet[6], data[8])
                     : clamp(creet[6] - 0.005 * creet[6], data[8], data[9]);
                   var _Q_ = wHeight * 0.85 < cy$0 + creet[6] ? 1 : 0;
                   return _Q_ ? contaminate(data, 1., creet) : _Q_;
                  }
                  if(cy$0 - creet[6] < wHeight * 0.15){creet[5] = 0; return 0;}
                  var
                   grid = data[10],
                   match = cellFromPos(creet[2], data),
                   cy = match[2],
                   cx = match[1],
                   _M_ = neighborCells([0, cx, cy]),
                   _N_ = caml_call1(Grid[8], grid),
                   _O_ = caml_call1(caml_call1(Stdlib_List[23], _N_), _M_),
                   _P_ = caml_call1(Stdlib_List[14], _O_),
                   overlap =
                     caml_call1
                      (caml_call1
                        (Stdlib_List[44],
                         function(other){
                          var _R_ = other[1] !== creet[1] ? 1 : 0;
                          if(! _R_) return _R_;
                          var
                           match = creet[2],
                           y1 = match[2],
                           x1 = match[1],
                           match$0 = other[2],
                           y2 = match$0[2],
                           x2 = match$0[1],
                           dx = x1 - x2,
                           dy = y1 - y2,
                           r = creet[6] + other[6];
                          return dx * dx + dy * dy <= r * r ? 1 : 0;
                         }),
                       _P_);
                  caml_call2
                   (Stdlib_List[18],
                    function(other){
                     toContaminate[1] = [0, other, toContaminate[1]];
                     return 0;
                    },
                    overlap);
                  return 2 === status
                          ? (creet
                             [6]
                            = clamp(creet[6] + 0.005 * creet[6], data[8], data[9]),
                            0)
                          : 3
                            === status
                            ? (creet
                               [6]
                              =
                               clamp(creet[6] - 0.005 * creet[6], data[8] * 0.85, data[9]),
                              0)
                            : (creet
                               [6]
                              = clamp(creet[6] - 0.005 * creet[6], data[8], data[9]),
                              0);
                 },
                 data[4]);
               var _K_ = 0.1;
               caml_call2
                (Stdlib_List[18],
                 function(_L_){return contaminate(data, _K_, _L_);},
                 toContaminate[1]);
               data[1] =
                caml_call2
                 (Stdlib_List[34],
                  function(c){return 0 === c[5] ? 1 : 0;},
                  data[4]);
               return gameIteration(data);
              }
              var match = data[14];
              if(! match) return caml_call1(Lwt[4], 0);
              var spr = match[1];
              return updateFullCanvas(data, spr[5]);
             });
   }
   function mousePositionOnCanvas(event, data){
    var
     canvas = data[2],
     rect = canvas.getBoundingClientRect(),
     mx = event.clientX - rect.left,
     my = event.clientY - rect.top;
    return [0, mx, my];
   }
   function generateCreet(id, speed, base_radius, canvas){
    var
     _J_ = generateRandomDirection(0),
     newCreet =
       [0,
        id,
        [0, canvas.width / 2., canvas.height / 2.],
        _J_,
        speed,
        0,
        base_radius];
    return newCreet;
   }
   function updateCanvasSize(canvas){
    var
     t34 = Js_of_ocaml_Dom_html[8],
     inner_w = t34.innerWidth,
     t35 = Js_of_ocaml_Dom_html[8],
     inner_h = t35.innerHeight,
     scale = caml_call2(Stdlib_Float[23], inner_w / 1920., inner_h / 1080.),
     t36 = 1920. * scale | 0;
    canvas.width = t36;
    var t38 = 1080. * scale | 0;
    canvas.height = t38;
    var t42 = canvas.style;
    t42.position = "absolute";
    var
     left = ((inner_w | 0) - canvas.width | 0) / 2 | 0,
     top = ((inner_h | 0) - canvas.height | 0) / 2 | 0,
     _H_ = caml_call1(Stdlib[33], left),
     t46 = caml_jsstring_of_string(caml_call2(Stdlib[28], _H_, cst_px)),
     t47 = canvas.style;
    t47.left = t46;
    var
     _I_ = caml_call1(Stdlib[33], top),
     t49 = caml_jsstring_of_string(caml_call2(Stdlib[28], _I_, cst_px$0)),
     t50 = canvas.style;
    t50.top = t49;
    return scale;
   }
   function loadImage(src){
    var
     img = caml_call1(Js_of_ocaml_Dom_html[68], Js_of_ocaml_Dom_html[2]),
     match = caml_call1(Lwt[1], 0),
     wakener = match[2],
     promise = match[1],
     t51 =
       caml_call1
        (Js_of_ocaml_Dom[10],
         function(param){
          caml_call2(Lwt[52], wakener, img);
          return Js_of_ocaml_Js[8];
         });
    img.onload = t51;
    var
     t53 =
       caml_call1
        (Js_of_ocaml_Dom[10],
         function(param){
          var _G_ = caml_call2(Stdlib[28], cst_Failed_to_load_image, src);
          caml_call1(Lwt[44], _G_);
          return Js_of_ocaml_Js[8];
         });
    img.onerror = t53;
    var t55 = caml_jsstring_of_string(src);
    img.src = t55;
    return promise;
   }
   function generateDataInitalCreets(data){
    var canvas = data[2];
    data[4] = 0;
    var _B_ = data[4];
    data[4] =
     [0, generateCreet(0, 4. * data[5], data[8] * data[5], canvas), _B_];
    var _C_ = data[4];
    data[4] =
     [0, generateCreet(1, 4. * data[5], data[8] * data[5], canvas), _C_];
    var _D_ = data[4];
    data[4] =
     [0, generateCreet(2, 4. * data[5], data[8] * data[5], canvas), _D_];
    var _E_ = data[4];
    data[4] =
     [0, generateCreet(3, 4. * data[5], data[8] * data[5], canvas), _E_];
    var _F_ = data[4];
    data[4] =
     [0, generateCreet(4, 4. * data[5], data[8] * data[5], canvas), _F_];
   }
   function tryLoadingSprites(onReady, data, iterations){
    if(3 < iterations) return Lwt[36];
    var match = data[14];
    if(match){var sprites = match[1]; return caml_call1(onReady, sprites);}
    var
     healthyCreetP = loadImage(cst_css_healthyCreet_png),
     sickCreetP = loadImage(cst_css_sickCreet_png),
     meanCreetP = loadImage(cst_css_meanCreet_png),
     berserkCreetP = loadImage(cst_css_berserkCreet_png),
     gameOverBackP = loadImage(cst_css_gameOver_png),
     menuBackP = loadImage(cst_css_menu_jpg),
     ppx_lwt_0 =
       caml_call3
        (Lwt[81],
         function(exn){
          try{throw caml_maybe_attach_backtrace(exn, 0);}
          catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
         },
         gameOverBackP,
         function(gameOverB){
          return caml_call3
                  (Lwt[81],
                   function(exn){
                    try{throw caml_maybe_attach_backtrace(exn, 0);}
                    catch(exn){
                     var exn$0 = caml_wrap_exception(exn);
                     return exn$0;
                    }
                   },
                   healthyCreetP,
                   function(healthy){
                    return caml_call3
                            (Lwt[81],
                             function(exn){
                              try{throw caml_maybe_attach_backtrace(exn, 0);}
                              catch(exn){
                               var exn$0 = caml_wrap_exception(exn);
                               return exn$0;
                              }
                             },
                             sickCreetP,
                             function(sick){
                              return caml_call3
                                      (Lwt[81],
                                       function(exn){
                                        try{throw caml_maybe_attach_backtrace(exn, 0);}
                                        catch(exn){
                                         var exn$0 = caml_wrap_exception(exn);
                                         return exn$0;
                                        }
                                       },
                                       berserkCreetP,
                                       function(berserk){
                                        return caml_call3
                                                (Lwt[81],
                                                 function(exn){
                                                  try{throw caml_maybe_attach_backtrace(exn, 0);}
                                                  catch(exn){
                                                   var exn$0 = caml_wrap_exception(exn);
                                                   return exn$0;
                                                  }
                                                 },
                                                 meanCreetP,
                                                 function(mean){
                                                  return caml_call3
                                                          (Lwt[81],
                                                           function(exn){
                                                            try{throw caml_maybe_attach_backtrace(exn, 0);}
                                                            catch(exn){
                                                             var exn$0 = caml_wrap_exception(exn);
                                                             return exn$0;
                                                            }
                                                           },
                                                           menuBackP,
                                                           function(menuB){
                                                            data[14] =
                                                             [0, [0, healthy, sick, mean, berserk, gameOverB, menuB]];
                                                            return Lwt[36];
                                                           });
                                                 });
                                       });
                             });
                   });
         });
    return caml_call3
            (Lwt[81],
             function(exn){
              try{throw caml_maybe_attach_backtrace(exn, 0);}
              catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
             },
             ppx_lwt_0,
             function(param){
              return tryLoadingSprites(onReady, data, iterations + 1 | 0);
             });
   }
   function duplicateCreet(data, healthyCreets, index){
    var creetOpt = caml_call2(Stdlib_List[9], healthyCreets, index);
    if(! creetOpt) return;
    var
     crt = creetOpt[1],
     _v_ = data[4],
     _w_ = crt[6],
     _x_ = crt[5],
     _y_ = crt[4],
     _z_ = crt[3],
     _A_ = crt[2];
    data[4] =
     [0,
      [0, caml_call1(Stdlib_List[1], data[4]), _A_, _z_, _y_, _x_, _w_],
      _v_];
   }
   function reproduceCreet(data){
    var
     prevId = data[18],
     ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js[1], 5.);
    return caml_call3
            (Lwt[81],
             function(exn){
              try{throw caml_maybe_attach_backtrace(exn, 0);}
              catch(exn){var exn$0 = caml_wrap_exception(exn); return exn$0;}
             },
             ppx_lwt_0,
             function(param){
              if(data[18] === prevId && data[1]){
               var _t_ = data[17];
               if(caml_call1(Stdlib_List[1], data[4]) < _t_){
                var
                 healthyCreets =
                   caml_call2
                    (Stdlib_List[44],
                     function(creet){return 0 === creet[5] ? 1 : 0;},
                     data[4]),
                 creetQuantity = caml_call1(Stdlib_List[1], healthyCreets);
                if(1 === creetQuantity)
                 duplicateCreet(data, healthyCreets, 0);
                else{
                 var
                  _u_ = caml_call1(Stdlib[33], creetQuantity),
                  t64 =
                    caml_jsstring_of_string
                     (caml_call2(Stdlib[28], cst_Prev, _u_)),
                  t65 = Js_of_ocaml_Firebug[1];
                 t65.log(t64);
                 duplicateCreet
                  (data,
                   healthyCreets,
                   caml_call1(Stdlib_Random[5], creetQuantity - 1 | 0));
                }
                return reproduceCreet(data);
               }
              }
              return Lwt[36];
             });
   }
   function restartGame(data){
    data[1] = 1;
    data[11] = -1;
    data[12] = _f_;
    data[18] = data[18] + 1 | 0;
    generateDataInitalCreets(data);
    rebuildGrid(data);
    caml_call1(Lwt[11], function(param){return reproduceCreet(data);});
    return caml_call1
            (Lwt[11],
             function(param){
              return tryLoadingSprites
                      (function(sprites){return gameIteration(data);}, data, 0);
             });
   }
   var
    t88 =
      caml_call1
       (Js_of_ocaml_Dom[10],
        function(param){
         caml_call1(Stdlib_Random[3], 0);
         var
          doc = Js_of_ocaml_Dom_html[2],
          match = caml_call1(Js_of_ocaml_Dom_html[3], cst_draw_zone$0);
         if(match){
          var
           div = match[1],
           canvas = caml_call1(Js_of_ocaml_Dom_html[111], doc);
          canvas.id = "canvas";
          var baseScale = updateCanvasSize(canvas);
          caml_call2(Js_of_ocaml_Dom[5], div, canvas);
          var
           t70 = Js_of_ocaml_Dom_html[1],
           ctx = canvas.getContext(t70),
           rad = 40. * baseScale,
           data =
             [0,
              0,
              canvas,
              0.016,
              0,
              baseScale,
              ctx,
              4.,
              rad,
              rad * 4.,
              caml_call1(Grid[1], 1024),
              -1,
              _h_,
              _g_,
              0,
              1,
              0,
              10,
              0,
              0];
          generateDataInitalCreets(data);
          rebuildGrid(data);
          caml_call1
           (Lwt[11],
            function(param){
             return tryLoadingSprites
                     (function(sprites){
                       return updateFullCanvas(data, sprites[6]);
                      },
                      data,
                      0);
            });
          var
           t76 =
             caml_call1
              (Js_of_ocaml_Dom_html[10],
               function(t72){
                var match = caml_call1(Js_of_ocaml_Js[6][10], t72.key);
                if(! match) return Js_of_ocaml_Js[7];
                var
                 key = match[1],
                 key$0 = runtime.caml_string_of_jsstring(key);
                a:
                {
                 if(key$0 !== "r" && key$0 !== "R"){
                  if(key$0 !== "p" && key$0 !== cst_P){
                   var
                    _r_ = key$0 === "m" ? 1 : 0,
                    _s_ = _r_ || (key$0 === cst_P ? 1 : 0);
                   if(! _s_) break a;
                   var match$0 = data[16];
                   if(match$0){
                    var mus = match$0[1], t74 = ! ! (1 - (mus.muted | 0));
                    mus.muted = t74;
                   }
                   break a;
                  }
                  if(! data[15]) break a;
                  var
                   audio =
                     caml_call1
                      (Js_of_ocaml_Dom_html[108], Js_of_ocaml_Dom_html[2]);
                  audio.src = "/css/music.mp3";
                  var t59 = Js_of_ocaml_Js[7];
                  audio.loop = t59;
                  audio.volume = 0.5;
                  audio.play();
                  data[16] = [0, audio];
                  data[15] = 0;
                  restartGame(data);
                  break a;
                 }
                 var _p_ = 1 - data[1], _q_ = _p_ ? 1 - data[15] : _p_;
                 if(_q_) restartGame(data);
                }
                return Js_of_ocaml_Js[7];
               }),
           t77 = Js_of_ocaml_Dom_html[8];
          t77.onkeydown = t76;
          var
           t78 =
             caml_call1
              (Js_of_ocaml_Dom_html[10],
               function(ev){
                if(! data[1]) return Js_of_ocaml_Js[7];
                rebuildGrid(data);
                var
                 mousePos = mousePositionOnCanvas(ev, data),
                 grid = data[10],
                 my = mousePos[2],
                 mx = mousePos[1],
                 match = cellFromPos([0, mx, my], data),
                 cy = match[2],
                 cx = match[1],
                 _i_ = neighborCells([0, cx, cy]),
                 _j_ = caml_call1(Grid[8], grid),
                 _k_ = caml_call1(caml_call1(Stdlib_List[23], _j_), _i_),
                 _l_ = caml_call1(Stdlib_List[14], _k_),
                 _m_ =
                   caml_call1
                    (caml_call1
                      (Stdlib_List[44],
                       function(creet){
                        var
                         match = creet[2],
                         y = match[2],
                         x = match[1],
                         dx = mx - x,
                         dy = my - y,
                         rad = creet[6] + 5. * data[5];
                        return dx * dx + dy * dy <= rad * rad ? 1 : 0;
                       }),
                     _l_),
                 param =
                   caml_call1
                    (caml_call1
                      (Stdlib_List[59],
                       function(a, b){return runtime.caml_int_compare(b[1], a[1]);}),
                     _m_);
                if(param)
                 var x = param[1], match$0 = [0, x];
                else
                 var match$0 = 0;
                if(! match$0) return Js_of_ocaml_Js[7];
                var c = match$0[1];
                data[11] = c[1];
                var
                 my$0 = mousePos[2],
                 mx$0 = mousePos[1],
                 match$1 = c[2],
                 cy$0 = match$1[2],
                 cx$0 = match$1[1];
                data[12] = [0, cx$0 - mx$0, cy$0 - my$0];
                data[19] = data[19] + 1 | 0;
                var tempToken = data[19];
                c[3] = generateRandomDirection(0);
                caml_call1
                 (Lwt[11],
                  function(param){
                   var ppx_lwt_0 = caml_call1(Js_of_ocaml_lwt_Lwt_js[1], 3.);
                   return caml_call3
                           (Lwt[81],
                            function(exn){
                             try{throw caml_maybe_attach_backtrace(exn, 0);}
                             catch(exn){
                              var exn$0 = caml_wrap_exception(exn);
                              return exn$0;
                             }
                            },
                            ppx_lwt_0,
                            function(param){
                             var
                              _n_ = data[19] === tempToken ? 1 : 0,
                              _o_ = _n_ ? data[11] === c[1] ? 1 : 0 : _n_;
                             if(_o_) resetGrab(data);
                             return Lwt[36];
                            });
                  });
                return Js_of_ocaml_Js[7];
               }),
           t79 = data[2];
          t79.onmousedown = t78;
          var
           t80 =
             caml_call1
              (Js_of_ocaml_Dom_html[10],
               function(param){resetGrab(data); return Js_of_ocaml_Js[7];}),
           t81 = data[2];
          t81.onmouseup = t80;
          var
           t82 =
             caml_call1
              (Js_of_ocaml_Dom_html[10],
               function(param){resetGrab(data); return Js_of_ocaml_Js[7];}),
           t83 = data[2];
          t83.onmouseout = t82;
          var
           t84 =
             caml_call1
              (Js_of_ocaml_Dom_html[10],
               function(ev){
                data[13] = mousePositionOnCanvas(ev, data);
                return Js_of_ocaml_Js[7];
               }),
           t85 = data[2];
          t85.onmousemove = t84;
          var
           t86 =
             caml_call1
              (Js_of_ocaml_Dom[10],
               function(param){
                var previousScale = data[5];
                data[5] = updateCanvasSize(canvas);
                var ratio = data[5] / previousScale;
                data[8] = data[8] * ratio;
                data[9] = data[8] * 4.;
                data[7] = data[7] * ratio;
                caml_call2
                 (Stdlib_List[18],
                  function(creet){
                   creet[4] = data[7];
                   var match = creet[2], y = match[2], x = match[1];
                   creet[2] = [0, x * ratio, y * ratio];
                   creet[6] = creet[6] * ratio;
                   return 0;
                  },
                  data[4]);
                if(data[15])
                 caml_call1
                  (Lwt[11],
                   function(param){
                    return tryLoadingSprites
                            (function(sprites){
                              return updateFullCanvas(data, sprites[6]);
                             },
                             data,
                             0);
                   });
                return Js_of_ocaml_Js[7];
               }),
           t87 = Js_of_ocaml_Dom_html[8];
          t87.onresize = t86;
          return Js_of_ocaml_Js[7];
         }
         var t67 = Js_of_ocaml_Firebug[1];
         t67.log("Div not found");
         return Js_of_ocaml_Js[8];
        }),
    t89 = Js_of_ocaml_Dom_html[8];
   t89.onload = t88;
   var H42n42 = [0];
   runtime.caml_register_global(159, H42n42, "H42n42");
   return;
  }
  (globalThis));
