(* This file was generated by Eliom-distillery.
   Feel free to use it, modify it, and redistribute it as you wish. *)

let%server application_name = "h42n42"
let%client application_name = Eliom_client.get_application_name ()

(* Create a module for the application. See
   https://ocsigen.org/eliom/manual/clientserver-applications for more
   information. *)
module%shared App = Eliom_registration.App (struct
    let application_name = application_name
    let global_data_path = Some ["__global_data__"]
  end)

(* As the headers (stylesheets, etc) won't change, we ask Eliom not to
   update the <head> of the page when changing page. (This also avoids
   blinking when changing page in iOS). *)
let%client _ = Eliom_client.persist_document_head ()

let%server main_service =
  Eliom_service.create ~path:(Eliom_service.Path [])
    ~meth:(Eliom_service.Get Eliom_parameter.unit) ()

let%client main_service = ~%main_service

let%shared () =
  App.register ~service:main_service (fun () () ->
    Lwt.return
      Eliom_content.Html.F.(
        html
          (head
             (title (txt "h42n42"))
             [ css_link
                 ~uri:
                   (make_uri
                      ~service:(Eliom_service.static_dir ())
                      ["css"; "h42n42.css"])
                 () ])
          (body 
            [div ~a:[a_id "draw-zone"] []])))


          (* CLIENT CODE *)
[%%client
    open Js_of_ocaml
    open Js_of_ocaml_lwt


    type status = 
      | Healthy
      | Sick
      | Berserk
      | Mean

    type creet = {
      id: int;
      mutable pos : float * float;
      mutable dir : float * float;
      mutable speed : float;
      mutable status : status;
      mutable radius : float;
    }

    module Cell = struct
      type t = int * int
      let equal = (=)
      let hash = Hashtbl.hash
    end

    module Grid = Hashtbl.Make(Cell)

    type grid = creet list Grid.t
    
    type images = {
      healthyCreet: Dom_html.imageElement Js.t;
      sickCreet: Dom_html.imageElement Js.t;
      meanCreet : Dom_html.imageElement Js.t;
      berserkCreet : Dom_html.imageElement Js.t;
      gameOver : Dom_html.imageElement Js.t;
      menu : Dom_html.imageElement Js.t;
    }

    type data = {
      mutable isRunning: bool;
      windowCanvas: Dom_html.canvasElement Js.t;
      refresh_rate: float;
      mutable creets: creet list;
      mutable scale: float;
      canvaCtx: Dom_html.canvasRenderingContext2D Js.t;
      mutable baseSpeed: float;
      mutable baseRadius: float;
      mutable maxRadius: float;
      mutable grid: grid;
      mutable grabbedCreetId: int;
      mutable grabbedCreetOffset: (float * float);
      mutable mousePos: (float * float);
      mutable sprites : images option;
      mutable isInMenu : bool;
      mutable music : Dom_html.audioElement Js.t option;
      creetLimit: int;
      mutable gameId: int;
      mutable grabToken: int;
    }

    let generateRandomDirection () : (float * float) = 
      let a = Random.float (2. *. Float.pi) in
      (cos a, sin a)

    let spriteForCreet sprites creet =
      match creet.status with
      | Healthy -> sprites.healthyCreet
      | Sick -> sprites.sickCreet
      | Berserk -> sprites.berserkCreet
      | Mean -> sprites.meanCreet

    let probTurn crt = 
      let probability = 0.002 in
      if Random.float 1. < probability then
        crt.dir <- generateRandomDirection ()
    
    let clamp v min max =
      Float.max min (Float.min max v)
      
      let neighborCells (cx, cy) =
        [-1; 0; 1]
        |> List.concat_map (fun dx ->
          [-1; 0; 1]
          |> List.map (fun dy ->
              (cx + dx, cy + dy)
            )
          )

    let fix_pos crt ~w ~h =
      let x, y = crt.pos in
      let r = crt.radius in
      crt.pos <- (
        clamp x r (w -. r),
        clamp y r (h -. r)
      )

    let cellFromPos (x, y) data =
      (int_of_float (x /. (data.maxRadius *. 2.)),
        int_of_float (y /. (data.maxRadius *. 2.)))

    let rebound crt ~w ~h =
      let x, y = crt.pos in
      let dx, dy = crt.dir in
      let r = crt.radius in

      let dx =
        if x -. r <= 0. || x +. r >= w then -.dx else dx
      in
      let dy =
        if y -. r <= 0. || y +. r >= h then -.dy else dy
      in
      crt.dir <- (dx, dy)

    let sqr x = x *. x
      
    let creetDistance (x1, y1) (x2, y2) =
      sqr (x2 -. x1) +. sqr (y2 -. y1)
    
    let nearestHealthy data creet =
      let cx, cy = cellFromPos creet.pos data in
      neighborCells (cx, cy)
      |> List.filter_map (Grid.find_opt data.grid)
      |> List.concat
      |> List.filter (fun c -> c.status = Healthy)
      |> List.fold_left (fun acc other ->
          match acc with
          | None -> Some other
          | Some best ->
            if creetDistance creet.pos other.pos < creetDistance creet.pos best.pos
            then Some other
            else acc
        ) None

    let dirToward (x1, y1) (x2, y2) =
      let dx = x2 -. x1 in
      let dy = y2 -. y1 in
      let len = sqrt (dx *. dx +. dy *. dy) in
      if len = 0. then (0., 0.)
      else (dx /. len, dy /. len)

    let moveCircle crt data =
      let x, y = crt.pos in
      if data.grabbedCreetId = crt.id then
        let mx, my = data.mousePos in
        let vx, vy = data.grabbedCreetOffset in
        crt.pos <- (mx +. vx, my +. vy)
      else 
      match crt.status with
      | Mean ->
        begin match nearestHealthy data crt with
        | None ->
          let dx, dy = crt.dir in
          crt.pos <- (
            x +. dx *. crt.speed,
            y +. dy *. crt.speed
          )
        | Some target ->
          let dx, dy = dirToward crt.pos target.pos in
          crt.dir <- (dx, dy);
          crt.pos <- (
            x +. dx *. crt.speed,
            y +. dy *. crt.speed
          )
        end;
      | _ ->
        let dx, dy = crt.dir in
        crt.pos <- (
          x +. dx *. crt.speed,
          y +. dy *. crt.speed
        )

    let drawCircle creet data =
      match data.sprites with
      | None -> ()
      | Some sprites ->
        let img = spriteForCreet sprites creet in
        let ctx = data.canvaCtx in
        let x, y = creet.pos in
        let size = creet.radius *. 2. in

        ctx##drawImage_withSize
          img
          (x -. creet.radius)
          (y -. creet.radius)
          size
          size
        
    let handleCircle creet data wWidth wHeight =
      probTurn creet;
      moveCircle creet data;
      rebound creet ~w:wWidth ~h:wHeight;
      fix_pos creet ~w:wWidth ~h:wHeight;
      drawCircle creet data

    let rebuildGrid data =
      data.grid <- Grid.create 1024;
      List.iter (fun crt -> 
        let cell = cellFromPos crt.pos data in
        let lst =
          match Grid.find_opt data.grid cell with
          | Some l -> l
          | None -> []
        in
        Grid.replace data.grid cell (crt :: lst)
      ) data.creets

    let overlaps c1 c2 =
      let x1, y1 = c1.pos in
      let x2, y2 = c2.pos in
      let dx = x1 -. x2 in
      let dy = y1 -. y2 in
      let r = c1.radius +. c2.radius in
      (dx *. dx +. dy *. dy) <= (r *. r)


    let nearbyOverlaps grid creet data =
      let cx, cy = cellFromPos creet.pos data in
      neighborCells (cx, cy)
      |> List.filter_map (Grid.find_opt grid)
      |> List.concat
      |> List.filter (fun other -> 
        other.id <> creet.id && overlaps creet other
      )

    let handleContamination creet = 
      creet.status <- Sick;
      if Random.float 1. < 0.5 then
        if Random.float 1. < 0.1 then
          creet.status <- Berserk
        else if Random.float 1. < 0.1 then
          creet.status <- Mean
      else if Random.float 1. < 0.1 then
        if Random.float 1. < 0.1 then
          creet.status <- Mean
        else if Random.float 1. < 0.1 then
          creet.status <- Berserk
      else ()

    let contaminate data baseProbability creet =
      if creet.id = data.grabbedCreetId then () else
      let _ , cy = creet.pos in
      if (cy -. creet.radius) < ((float_of_int data.windowCanvas##.height) *. 0.2) then () else
      if Random.float 1. > baseProbability then () else
      match creet.status with
      | Healthy ->
        handleContamination creet
      | _ -> ()

    let resetGrab data =
      data.grabToken <- data.grabToken + 1;
      data.grabbedCreetId <- -1;
      data.grabbedCreetOffset <- (0., 0.)

    let updateFullCanvas data sprite =
      let wHeight = float_of_int data.windowCanvas##.height in
      let wWidth = float_of_int data.windowCanvas##.width in
      data.canvaCtx##clearRect 0. 0. wWidth wHeight;
      data.canvaCtx##drawImage_withSize sprite 0. 0. wWidth wHeight;
      Lwt.return ()

    let rec gameIteration (data: data) : unit Lwt.t =
      let%lwt () = Lwt_js.sleep data.refresh_rate in
      let wHeight = float_of_int data.windowCanvas##.height in
      let wWidth = float_of_int data.windowCanvas##.width in
      if not data.isRunning then begin
        match data.sprites with
        | Some spr ->  updateFullCanvas data spr.gameOver
        | None -> Lwt.return ()
      end else begin
        data.baseSpeed <- data.baseSpeed *. 1.0002;
        rebuildGrid data;
        data.canvaCtx##clearRect 0. 0. wWidth wHeight;
        List.iter (fun creet ->
          handleCircle creet data wWidth wHeight;
        ) data.creets;
        let toContaminate = ref [] in

        List.iter (fun creet ->
          creet.speed <- data.baseSpeed;
          let _ , cy = creet.pos in
          match creet.status with
          | Healthy ->
            if creet.radius < data.baseRadius then begin
              creet.radius <- clamp (creet.radius +. (0.005 *. creet.radius)) creet.radius data.baseRadius;
            end else begin
              creet.radius <- clamp (creet.radius -. (0.005 *. creet.radius)) data.baseRadius data.maxRadius;
            end;
            if (cy +. creet.radius) > (wHeight *. 0.85) then
              contaminate data 1. creet
          | status ->
            if (cy -. creet.radius) < (wHeight *. 0.15) then
              creet.status <- Healthy
            else
              let overlap = nearbyOverlaps data.grid creet data in
              List.iter (fun other -> 
                toContaminate := other :: !toContaminate
              ) overlap;
              if status = Berserk then begin
                creet.radius <- clamp (creet.radius +. (0.005 *. creet.radius)) data.baseRadius data.maxRadius
              end else if status = Mean then begin
                creet.radius <- clamp (creet.radius -. (0.005 *. creet.radius)) (data.baseRadius *. 0.85) data.maxRadius;
              end else begin
                creet.radius <- clamp (creet.radius -. (0.005 *. creet.radius)) data.baseRadius data.maxRadius;
              end;
        ) data.creets;

        List.iter (contaminate data 0.1) !toContaminate;
        
        data.isRunning <- (List.exists (fun c -> c.status = Healthy) data.creets);
        gameIteration data
      end

    let mousePositionOnCanvas event data =
      let canvas = data.windowCanvas in
      let rect = canvas##getBoundingClientRect in
      let mx =
        (float_of_int event##.clientX) -. rect##.left
      in
      let my =
        (float_of_int event##.clientY) -. rect##.top
      in
      (mx, my)
         

    let containsPoint creet (mx, my) data=
      let x, y = creet.pos in
      let dx = mx -. x in
      let dy = my -. y in
      let rad = creet.radius +. (5. *. data.scale) in
      (dx *. dx +. dy *. dy) <= (rad *. rad)


    let clickedCreets grid (mx, my) data =
      let cx, cy = cellFromPos (mx, my) data in
      neighborCells (cx, cy)
      |> List.filter_map (Grid.find_opt grid)
      |> List.concat
      |> List.filter (fun c -> 
          containsPoint c (mx, my) data
        )

      let hd_opt = function
        | [] -> None
        | x :: _ -> Some x

    let creetAtTopmost grid (mx, my) data =
      clickedCreets grid (mx, my) data
      |> List.sort(fun a b -> compare b.id a.id)
      |> hd_opt

    let generateCreet id speed base_radius canvas: creet=
      let newCreet = {
        id = id;
        pos = ((float_of_int canvas##.width) /. 2., (float_of_int canvas##.height) /. 2.);
        status = Healthy;
        speed = speed;
        dir = generateRandomDirection ();
        radius = base_radius;
      } in
      newCreet


    let updateCanvasSize canvas : float =
      let inner_w = float_of_int Dom_html.window##.innerWidth in
      let inner_h = float_of_int Dom_html.window##.innerHeight in
      let ref_h = 1080. in
      let ref_w = 1920. in
      let scale = Float.min (inner_w /. ref_w) (inner_h /. ref_h) in
      canvas##.width := int_of_float ((ref_w *. scale));
      canvas##.height := int_of_float ((ref_h *. scale));
      canvas##.style##.position := Js.string "absolute";
      let left = ((int_of_float inner_w) - canvas##.width) / 2 in
      let top = ((int_of_float inner_h) - canvas##.height) / 2 in
      canvas##.style##.left := Js.string (string_of_int left ^ "px");
      canvas##.style##.top := Js.string (string_of_int top ^ "px");
      scale

    let loadImage src : Dom_html.imageElement Js.t Lwt.t =
      let img = Dom_html.createImg Dom_html.document in
      let promise, wakener = Lwt.wait () in

      img##.onload := Dom.handler (fun _ -> 
        Lwt.wakeup wakener img;
        Js._false
      );
      img##.onerror := Dom.handler (fun _ ->
        Lwt.fail_with ("Failed to load image: " ^ src)
        |> ignore;
        Js._false;
      );
      img##.src := Js.string src;
      promise
    
    let playMusic src =
      let audio = Dom_html.createAudio Dom_html.document in
      audio##.src := Js.string src;
      audio##.loop := Js._true;
      audio##.volume := 0.5;
      ignore (audio##play);
      audio
    
    let loadSprites data : unit Lwt.t =
      let healthyCreetP = loadImage "/css/healthyCreet.png" in
      let sickCreetP = loadImage "/css/sickCreet.png" in
      let meanCreetP = loadImage "/css/meanCreet.png" in
      let berserkCreetP = loadImage "/css/berserkCreet.png" in
      let gameOverBackP = loadImage "/css/gameOver.png" in
      let menuBackP = loadImage "/css/menu.jpg" in

      let%lwt gameOverB = gameOverBackP
      and healthy = healthyCreetP
      and sick = sickCreetP
      and berserk = berserkCreetP
      and mean = meanCreetP
      and menuB = menuBackP in

      data.sprites <- Some {
        healthyCreet = healthy;
        meanCreet = mean;
        berserkCreet = berserk;
        sickCreet = sick;
        gameOver = gameOverB;
        menu = menuB;
      };

      Lwt.return_unit

    let generateDataInitalCreets data =
      let canvas = data.windowCanvas in
      data.creets <- [];
      data.creets <- (generateCreet 0 (4. *. data.scale) (data.baseRadius *. data.scale) canvas) :: data.creets;
      data.creets <- (generateCreet 1 (4. *. data.scale) (data.baseRadius *. data.scale) canvas) :: data.creets;
      data.creets <- (generateCreet 2 (4. *. data.scale) (data.baseRadius *. data.scale) canvas) :: data.creets;
      data.creets <- (generateCreet 3 (4. *. data.scale) (data.baseRadius *. data.scale) canvas) :: data.creets;
      data.creets <- (generateCreet 4 (4. *. data.scale) (data.baseRadius *. data.scale) canvas) :: data.creets


    let rec tryLoadingSprites ~(onReady: images -> unit Lwt.t) data iterations =
    if iterations > 3 then
      Lwt.return_unit
    else 
      match data.sprites with
        | None ->
          let%lwt () = loadSprites data in
            tryLoadingSprites ~onReady data (iterations+1)
        | Some sprites ->
          onReady sprites

      
    let duplicateCreet data healthyCreets index =
      let creetOpt = List.nth_opt healthyCreets index in
      match creetOpt with
      | None -> ()
      | Some crt ->
        data.creets <- {crt with id = (List.length data.creets)} :: data.creets

    let rec reproduceCreet data =
      let prevId = data.gameId in
      let%lwt () = Lwt_js.sleep 5. in
      if data.gameId = prevId && data.isRunning && (List.length data.creets) < data.creetLimit then begin
        let healthyCreets = List.filter (fun creet -> creet.status = Healthy) data.creets in
        let creetQuantity = List.length healthyCreets in
        if creetQuantity = 1 then begin
          duplicateCreet data healthyCreets 0
        end else begin
          Firebug.console##log (Js.string ("Prev : " ^ string_of_int creetQuantity));
          duplicateCreet data healthyCreets (Random.int (creetQuantity-1))
        end;
        reproduceCreet data
      end else begin
      Lwt.return_unit
      end

    let restartGame data =
      data.isRunning <- true;
      data.grabbedCreetId <- -1;
      data.grabbedCreetOffset <- (0., 0.);
      data.gameId <- data.gameId + 1;
      generateDataInitalCreets data;
      rebuildGrid data;
      Lwt.async (fun () ->
        reproduceCreet data
      );
      Lwt.async (fun () ->
        tryLoadingSprites
        ~onReady:(fun _sprites ->
          gameIteration data
        )
        data
        0
      )

    let () = 
      Dom_html.window##.onload := Dom.handler (fun _ ->
        Random.self_init ();
        let open Js_of_ocaml in
        let doc = Dom_html.document in
        match Dom_html.getElementById_opt "draw-zone" with
        | None ->
          let () = Firebug.console##log (Js.string "Div not found") in
          Js._false
        | Some div ->
          let canvas = Dom_html.createCanvas doc in
          canvas##.id := Js.string "canvas";
          let baseScale = updateCanvasSize canvas in
          Dom.appendChild div canvas;
          let ctx =
            (canvas##getContext Dom_html._2d_)
          in

          let rad = 40. *. baseScale in

          let data: data = {
            isRunning = false;
            windowCanvas = canvas;
            refresh_rate = 0.016;
            creets = [];
            scale = baseScale;
            canvaCtx = ctx;
            baseSpeed = 4.;
            baseRadius = rad;
            maxRadius = rad *. 4.;
            grid = (Grid.create 1024);
            grabbedCreetId = -1;
            grabbedCreetOffset = (0., 0.);
            mousePos = (0., 0.);
            sprites = None;
            isInMenu = true;
            music = None;
            creetLimit = 10;
            gameId = 0;
            grabToken = 0;
          } in
          
          generateDataInitalCreets data;
          rebuildGrid data;
          
          Lwt.async (fun () ->
            tryLoadingSprites 
            ~onReady:(fun sprites ->
              updateFullCanvas data sprites.menu
            )
            data
            0
          );
          
          Dom_html.window##.onkeydown :=
            Dom_html.handler (fun ev -> 
              match Js.Optdef.to_option ev##.key with
              | Some key ->
                let key = Js.to_string key in
                if key = "r" || key = "R" then begin
                  if not data.isRunning  && not data.isInMenu then
                    restartGame data
                end else if key = "p" || key = "P" then begin
                  if data.isInMenu then begin
                    data.music <- Some (playMusic "/css/music.mp3");
                    data.isInMenu <- false;
                    restartGame data
                  end;
                end else if key = "m" || key = "P" then begin
                  match data.music with 
                  | Some mus ->
                    mus##.muted := Js.bool (not (Js.to_bool mus##.muted))
                  | None -> ()
                end;
                Js._true
              | None -> ()
              ;
              Js._true
            );

          data.windowCanvas##.onmousedown :=
            Dom_html.handler (fun ev ->
              if not data.isRunning then 
                Js._true
              else begin
              rebuildGrid data;
              let mousePos = mousePositionOnCanvas ev data in
              match creetAtTopmost data.grid (mousePos) data with
              | None -> 
                Js._true
              | Some c ->
                  data.grabbedCreetId <- c.id;
                  let mx, my = mousePos in
                  let cx, cy = c.pos in
                  data.grabbedCreetOffset <- (cx -. mx, cy -. my);
                  data.grabToken <- data.grabToken + 1;
                  let tempToken = data.grabToken in
                  c.dir <- generateRandomDirection ();
                  Lwt.async (fun () ->
                    let%lwt () = Lwt_js.sleep 3.0 in
                      if data.grabToken = tempToken && data.grabbedCreetId = c.id then begin
                        resetGrab data;
                      end;
                      Lwt.return_unit  
                  );
                Js._true
              end
            );
            
          data.windowCanvas##.onmouseup :=
            Dom_html.handler (fun _ ->
              resetGrab data;
              Js._true
            );

          data.windowCanvas##.onmouseout :=
              Dom_html.handler (fun _ -> 
                resetGrab data;
                Js._true  
              );

          data.windowCanvas##.onmousemove :=
            Dom_html.handler (fun ev ->
              data.mousePos <- mousePositionOnCanvas ev data;
              Js._true  
            );

          Dom_html.window##.onresize := Dom.handler (fun _ ->
            let previousScale = data.scale in
            data.scale <- updateCanvasSize canvas;
            let ratio = data.scale /. previousScale in
            data.baseRadius <- data.baseRadius *. (ratio);
            data.maxRadius <- data.baseRadius *. 4.;
            data.baseSpeed <- data.baseSpeed *. ratio;
            List.iter (fun creet -> 
              creet.speed <- data.baseSpeed;
              let x,y = creet.pos in
              creet.pos <- (x *. ratio, y *. ratio);
              creet.radius <- creet.radius *. ratio;
            ) data.creets;
            if data.isInMenu then begin
              Lwt.async (fun () ->
                tryLoadingSprites 
                ~onReady:(fun sprites ->
                  updateFullCanvas data sprites.menu
                )
                data
                0
              )
            end;
            Js._true
          );
          Js._true
      )
]