(* This file was generated by Eliom-distillery.
   Feel free to use it, modify it, and redistribute it as you wish. *)

let%server application_name = "h42n42"
let%client application_name = Eliom_client.get_application_name ()

(* Create a module for the application. See
   https://ocsigen.org/eliom/manual/clientserver-applications for more
   information. *)
module%shared App = Eliom_registration.App (struct
    let application_name = application_name
    let global_data_path = Some ["__global_data__"]
  end)

(* As the headers (stylesheets, etc) won't change, we ask Eliom not to
   update the <head> of the page when changing page. (This also avoids
   blinking when changing page in iOS). *)
let%client _ = Eliom_client.persist_document_head ()

let%server main_service =
  Eliom_service.create ~path:(Eliom_service.Path [])
    ~meth:(Eliom_service.Get Eliom_parameter.unit) ()

let%client main_service = ~%main_service

let%shared () =
  App.register ~service:main_service (fun () () ->
    Lwt.return
      Eliom_content.Html.F.(
        html
          (head
             (title (txt "h42n42"))
             [ css_link
                 ~uri:
                   (make_uri
                      ~service:(Eliom_service.static_dir ())
                      ["css"; "h42n42.css"])
                 () ])
          (body 
            [div ~a:[a_id "draw-zone"] []])))


          (* CLIENT CODE *)
[%%client
    open Js_of_ocaml
    open Js_of_ocaml_lwt


    type status = 
      | Healthy
      | Sick
      | Berserk
      | Mean

    type creet = {
      id: int;
      mutable pos : float * float;
      mutable dir : float * float;
      speed : float;
      status : status;
      radius : float;
    }

    type data = {
      isRunning: bool;
      windowCanvas: Dom_html.canvasElement Js.t;
      refresh_rate: float;
      creet: creet;
      mutable scale: float;
    }

    let generateRandomDirection () : (float * float) = 
      let a = Random.float (2. *. Float.pi) in
      (cos a, sin a)

    let statusColor = function
      | Healthy -> "blue"
      | Sick -> "green"
      | Berserk -> "red"
      | Mean -> "purple"

    let probTurn crt = 
      let probability = 0.005 in
      if Random.float 1. < probability then
        crt.dir <- generateRandomDirection ()
    
    let clamp v min max =
      Float.max min (Float.min max v)

    let fix_pos crt ~w ~h data =
      let x, y = crt.pos in
      let r = (crt.radius *. data.scale) in
      crt.pos <- (
        clamp x r (w -. r),
        clamp y r (h -. r)
      )

    let rebound crt ~w ~h data =
      let x, y = crt.pos in
      let dx, dy = crt.dir in
      let r = (crt.radius *. data.scale) in

      let dx =
        if x -. r <= 0. || x +. r >= w then -.dx else dx
      in
      let dy =
        if y -. r <= 0. || y +. r >= h then -.dy else dy
      in
      crt.dir <- (dx, dy)

    let moveCircle crt =
      let x, y = crt.pos in
      let dx, dy = crt.dir in
      crt.pos <- (
        x +. dx *. crt.speed,
        y +. dy *. crt.speed
      )

    let drawCircle circle ctx data =
      let x, y = circle.pos in
      ctx##beginPath;
      ctx##arc x y (circle.radius *. data.scale) 0. (Float.pi*. 2.) Js._false;
      (* Firebug.console##log data.scale; *)
      ctx##.fillStyle := Js.string (statusColor circle.status);
      ctx##fill;
      ctx##stroke
      

    let handleCircle circle data =
      let ctx =
        (data.windowCanvas##getContext Dom_html._2d_)
      in
      let wHeight = float_of_int data.windowCanvas##.height in
      let wWidth = float_of_int data.windowCanvas##.width in
      ctx##clearRect 0. 0. wWidth wHeight;
      ctx##.fillStyle := Js.string "white";
      ctx##fillRect 0. 0. wWidth wHeight;

      ignore circle.status;
      ignore circle.id;
      let _ = Mean in
      let _ = Berserk in
      let _ = Sick in
      probTurn circle;
      moveCircle circle;
      rebound circle ~w:wWidth ~h:wHeight data;
      fix_pos circle ~w:wWidth ~h:wHeight data;
      drawCircle circle ctx data

    let rec gameIteration (data: data) : unit Lwt.t =
      let%lwt () = Lwt_js.sleep data.refresh_rate in
      
      if not data.isRunning then
        Lwt.return()
      else begin
        handleCircle data.creet data;
        gameIteration data
      end
      
    let resizeCanvas canvas : float = 
      let inner_w = float_of_int Dom_html.window##.innerWidth in
      let inner_h = float_of_int Dom_html.window##.innerHeight in
      let ref_h = 1080. in
      let ref_w = 1920. in
      let scale = Float.min (inner_w /. ref_w) (inner_h /. ref_h) in
      canvas##.width := int_of_float ((ref_w *. scale) *. 0.8);
      canvas##.height := int_of_float ((ref_h *. scale) *. 0.8);
      canvas##.style##.position := Js.string "absolute";
      let left = ((int_of_float inner_w) - canvas##.width) / 2 in
      let top = ((int_of_float inner_h) - canvas##.height) / 2 in
      canvas##.style##.left := Js.string (string_of_int left ^ "px");
      canvas##.style##.top := Js.string (string_of_int top ^ "px");
      let ctx =
        (canvas##getContext Dom_html._2d_)
      in
      ctx##.fillStyle := Js.string "white";
      ctx##fillRect 0. 0. (float_of_int canvas##.width) (float_of_int canvas##.height);
      scale

    let () = 
      Dom_html.window##.onload := Dom.handler (fun _ ->
        let open Js_of_ocaml in
        let doc = Dom_html.document in
        match Dom_html.getElementById_opt "draw-zone" with
        | None ->
          let () = Firebug.console##log (Js.string "Div not found") in
          Js._false
        | Some div ->
          let canvas = Dom_html.createCanvas doc in
          let baseScale = resizeCanvas canvas in
          Dom.appendChild div canvas;

          let circle: creet = {
            id = 0;
            pos = (float_of_int canvas##.width, float_of_int canvas##.height);
            status = Healthy;
            speed = 20.;
            dir = generateRandomDirection ();
            radius = 15.;
          } in
          let data: data = {
            isRunning = true;
            windowCanvas = canvas;
            refresh_rate = 0.016;
            creet = circle;
            scale = baseScale;
          } in

          Dom_html.window##.onresize := Dom.handler (fun _ -> 
            data.scale <- resizeCanvas canvas;
            Js._true
          );
  
          let () = Lwt.async (fun () -> gameIteration data) in
          Js._true
      )
]